config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :cohorts
      resources :courses
      resources :static
      resources :admin_users
      resources :students
      
      root to: "users#index"
    end
    resources :cohort_users
    
  resources :cohorts
  resources :courses
  resources :static do 
    resources :students
  end 
  devise_for :users, skip: [:registration]
  root to: 'static#homepage'
  
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :cohort_users, dependent: :destroy
  # has_many :instructors, through: :cohort_users
  has_many :users, through: :cohort_users
  has_one :instructor, -> { where(type: 'Instructor') }, :class_name => "User"
  
end

app/controllers/admin/cohorts_controller.rb
module Admin
  class CohortsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Cohort.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Cohort.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  def index
    @cohorts = Cohort.all
    @user = current_user
    @users = User.all
    
     
  end

  def new
    @cohort = Cohort.new
    @courses = Course.all.map{ |c| [c.name, c.id] }
    @users = User.all.map{ |c| [c.first_name, c.id, c.role] }
  end

  def create
  
    @cohort = Cohort.create(cohort_params) 
    puts "checking for cohort"

    if @cohort
			redirect_to cohorts_path, notice: 'Your cohort was successfully created'
		else
			render :new
		end
    
  end

  def show
    @cohort = set_cohort
    @cohort_user=CohortUser.new
    @users = User.all
    @users = User.all.map{|user| [user.first_name, user.id]}
  end
   
  def update

    if @cohort.update(cohort_params)
      redirect_to cohorts_path, notice: 'Your cohort was successfully edited'
    else
      render :edit
    end
  end
  
  def edit
    @cohort = Cohort.find(params[:id])
    @courses = Course.all.map{ |c| [c.name, c.id] }
    @users = User.all.map{ |c| [c.first_name, c.id, c.role] }
    
  end

  def destroy
    set_cohort.delete

    respond_to do |format|
      format.html
      format.js { render json: @cohorts }
    end
  end
 

  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :instructor,:course_id, :user_id)
  end

  def set_cohort
    @cohort = Cohort.find(params[:id])
  end
end

app/views/cohorts/_cohort.html.erb
<% @cohorts.each do |cohort| %>
  <tr id="cohort<%= cohort.id %>">
    <td>
      <%= cohort.id %>
    </td>
    <td>
      <%= cohort.name.upcase %>
    </td>
    <td>
      <%= cohort.start_date.strftime("%d/%m/%Y") %>
    </td>
    <td>
      <%= cohort.end_date.strftime("%d/%m/%Y") %>
    </td>
    <td>
     <h1> <%= cohort.user_id %></h1> 
    </td>
    <td> 
      <span><%= link_to '', edit_cohort_path(cohort), id: "edit_#{cohort.id}", class: "fas fa-pencil-alt index-icons" %></span>
    </td>
    <td>
      <span><%= link_to '', cohort_path(cohort), remote: true, method: :delete, class: "fas fa-trash-alt index-icons", id: "#{cohort.id}", data: { confirm: 'Are you sure?' } %></span>
    </td>
    <td>
      
    </td> 
    <td>
      <span><%= link_to '', cohort_path(cohort), class: "fas fa-folder-open index-icons" %></span>
    </td>  
  </tr>
  <% end %>
      

app/views/cohorts/_edit-form.html.erb
<%= form_for @cohort, class: "form-horizontal" do |c| %>
  <% if @cohort.errors.any? %>
  <% @cohort.errors.full_messages.each do |error| %>
  <%= js add_gritter(error, title: "School App Notification", sticky: false) %>
  <% end %>
<% end %>

  <div class="form-group">   
    <%= c.label :name, class: "col-sm-2 control-label" %>
    <%= c.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">   
    <%= c.label :start_date, class: "col-sm-2 control-label" %>
    <%= c.date_field :start_date, class: "form-control" %>
  </div>
  <div class="form-group">   
    <%= c.label :end_date, class: "col-sm-2 control-label" %>
    <%= c.date_field :end_date, class: "form-control" %>
  </div>
  <%# <div class="form-group">    %>
    <%# <%= c.label :course_id, class: "col-sm-2 control-label" %>
    <%# <%= c.select :course_id, options_for_select(@courses, @cohort.course_id), class: "form-control" %>
  </div>
  <div class="form-group">   
    <%= c.label :instructor, class: "col-sm-2 control-label cust-form" %>
    
    <%= c.select :user_id, options_for_select(@users, @cohort.user_id), class: "form-control" %>
    
  </div>
  
  <button type="submit" class="btn btn-warning btn-lg btn-block">
    Save
  </button>

<% end %>

app/views/cohorts/_form.html.erb
<%= form_for @cohort, class: "form-horizontal" do |c| %>
  <% if @cohort.errors.any? %>
  <% @cohort.errors.full_messages.each do |error| %>
  <%= js add_gritter(error, title: "School App Notification", sticky: false) %>
  <% end %>
<% end %>

  <div class="form-group">   
    <%= c.label :name, class: "col-sm-2 control-label" %>
    <%= c.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">   
    <%= c.label :start_date, class: "col-sm-2 control-label" %>
    <%= c.date_field :start_date, class: "form-control" %>
  </div>
  <div class="form-group">   
    <%= c.label :end_date, class: "col-sm-2 control-label" %>
    <%= c.date_field :end_date, class: "form-control" %>
  </div>
  <div class="form-group">   
    <%= c.label :Instructor, class: "col-sm-2 control-label" %>  
    
    <%= c.select :user_id, options_for_select(@users, @cohort.user_id), class: "form-control" %>
   
  </div>
  
  <button type="submit" class="btn btn-warning btn-lg btn-block">
    Save
  </button>

<% end %>

app/views/cohorts/delete.js.erb
let const<%= @cohort.id %> = document.querySelector("#cohort" + <%= @cohort.id %>);
const<%= @cohort.id %>.remove();

app/views/cohorts/destroy.js.erb
let const<%= @cohort.id %> = document.querySelector("#cohort" + <%= @cohort.id %>);
const<%= @cohort.id %>.remove();

app/views/cohorts/edit.html.erb
<hr class="bg-warning"><H2>Edit Cohort</H2><hr class="bg-warning">

<%= render 'edit-form' %>

app/views/cohorts/index.html.erb
<hr class="bg-warning"><h2>Cohorts</h2><hr class="bg-warning">

<table class="table table-hover table-striped">
  <thead>
    <tr class="tb-header">
      <th>
        #
      </th>
      <th>
        Name
      </th>
      <th>
        Start Date
      </th>
      <th>
        End Date
      </th>
      <th>
        Instructor
      </th>
      <th>
        
      </th>
      <th>
       
      </th>
      <th>
        
      </th>
      <th>
        <button class="btn btn-sm btn-warning"><%= link_to 'Add New', new_cohort_path(@cohorts) %>
        </button>
      </th>
    </tr>
  </thead>
  
  <tbody>
  <%= render partial: "cohort", locals: {cohorts: @cohorts} %>
  </tbody>
</table>

app/views/cohorts/new.html.erb
<hr class="bg-warning"><h2>Create New Cohort</h2><hr class="bg-warning">


<%= render 'form' %>

app/views/cohorts/show.html.erb
<hr class="bg-warning"><h2>Students</h2><hr class="bg-warning">

  <div class="form-group">    
    <%= form_with model: @cohort_user do |form| %>
      <%= form.select(:users_ids, options_for_select(@users), 
        { prompt: 'Add Students'}
        ) %>
      <%= form.hidden_field :cohort_id, value: @cohort.id %>
      <%= form.submit%>
    <% end %> 
  </div>

<% @cohort.users.each do |user| %>
<div class="container-fluid ml-4 mt-1">
  <div class="row media">
    <div class="col-md-2">
      <div class="media-left media-top">
        <a href="#">
          <%= image_tag(user.email, size: "66", class: "photo") %>
        </a>
      </div>
    </div>
    <div class="row col-md-6">
      <div>
        <p><span>Name: </span><%= user.full_name %></p>
        <p><span>Age: </span><%= user.age %></p>
        <p><span>Education: </span><%= user.education %></p>
    
      </div>
    </div>
    <div class="col-md-3">
      <span>
        <i class="fas fa-pencil-alt index-icons2"></i> 
        
        </span>
      <span>
        <%= link_to '', cohort_path(@cohort), remote: true, method: :delete, class: "fas fa-trash-alt index-icons", id: "#{user.id}", data: { confirm: 'Are you sure?' } %> 
      </span>
    </div>
  </div>
</div>
<% end %>