config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :cohorts
      resources :courses
      resources :static
      resources :admin_users
      resources :students
      
      root to: "users#index"
    end
    resources :cohort_users
    
  resources :cohorts
  resources :courses
  resources :static do 
    resources :students
  end 
  devise_for :users, skip: [:registration]
  root to: 'static#homepage'
  
end

app/models/admin_user.rb
class AdminUser < User
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :instructor, -> { where role: 'instructor' }
  scope :student, -> { where role: 'student' }
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :cohort_users, dependent: :destroy
  # has_many :instructors, through: :cohort_users
  has_many :users, through: :cohort_users
  has_one :instructor, -> { where(type: 'Instructor') }, :class_name => "User"
  
end

app/models/cohort_user.rb
class CohortUser < ApplicationRecord
  belongs_to :cohort
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  validates_presence_of :name, :hours

  scope :courses_for, ->(user) { where(user_id: user.id) } 
end

app/models/instructor.rb
class Instructor < User
  
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/student.rb
class Student < User
  validates_presence_of :first_name, :last_name, :age, :education
  belongs_to :cohort
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # after_initialize :set_defaults
  validates_presence_of :first_name, :last_name, :age, :education, :salary
  validates :age, numericality: { only_integer: true, greater_than: 0, less_than: 150.0, alert: "Enter valid age" }
  validates :salary, numericality: {only_integer: true, greater_than: 0, alert: "Enter valid number"}
  has_many :cohort_users
  has_many :cohorts, through: :cohort_users

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end
  scope :instructor, -> { where role: 'instructor' }
  scope :student, -> { where role: 'student' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception
  helper_method :full_name, :current_user
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def full_name
    fname = User.first_name.capitalize
    lname = User.last_name.capitalize
    full_name = "fname" + " " + "lname"
  end

  def admin_types
    ['AdminUser']
  end

  private
  
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(root_path)
  end
    
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  def index
    @cohorts = Cohort.all
    @user = current_user
    @users = User.all
    
     
  end

  def new
    @cohort = Cohort.new
    @courses = Course.all.map{ |c| [c.name, c.id] }
    @users = User.all.map{ |c| [c.first_name, c.id, c.role] }
  end

  def create
  
    @cohort = Cohort.create(cohort_params) 
    puts "checking for cohort"

    if @cohort
			redirect_to cohorts_path, notice: 'Your cohort was successfully created'
		else
			render :new
		end
    
  end

  def show
    @cohort = set_cohort
    @cohort_user=CohortUser.new
    @users = User.all
    @users = User.all.map{|user| [user.first_name, user.id]}
  end
   
  def update

    if @cohort.update(cohort_params)
      redirect_to cohorts_path, notice: 'Your cohort was successfully edited'
    else
      render :edit
    end
  end
  
  def edit
    @cohort = Cohort.find(params[:id])
    @courses = Course.all.map{ |c| [c.name, c.id] }
    @users = User.all.map{ |c| [c.first_name, c.id, c.role] }
    
  end

  def destroy
    set_cohort.delete

    respond_to do |format|
      format.html
      format.js { render json: @cohorts }
    end
  end
 

  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :instructor,:course_id, :user_id)
  end

  def set_cohort
    @cohort = Cohort.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  
  def index
    # @courses = Course.courses_for current_user
    @courses = Course.all
    @users = User.all
  end

  def new
    @course = Course.new
  end
  
  def create
    @course = Course.create(
      name: params[:course][:name],
      hours: params[:course][:hours],
    ) 
    redirect_to courses_path, notice: 'Your course was successfully created'
  end

  def show
    @cohort = Cohort.all
  end

  def update
    authorize @course 
    
    if @course.update(course_params)
      redirect_to courses_path, notice: 'Your course was successfully edited'
    else
      render :edit
    end
  end

  def edit
    # authorize @course 
  end

  def destroy
    set_course.delete
    
    respond_to do |format|
      format.html
      format.js { render '/courses/delete.js.erb'}
      format.json { render json: @courses }
    end
  end
   
  private

  def course_params
    params.require(:course).permit(:course_id, :name, :hours)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
    @users = User.all
    @user = current_user
    if admin_types.include?(current_user.type)
    end
  end
 
  def edit
    @user = current_user
    if admin_types.include?(current_user.type)
    end

  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
  end

  def show
    @users = User.all
    @courses = Course.all
    @cohorts = Cohort.all
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_path, notice: 'Your user was successfully edited'
    else
      render :edit
    end
  end

  def destroy
    
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :education, :salary, :role, :course_id, :cohort_id)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    @users = User.all
    @cohorts = Cohort.all
  end

  def show
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new]
  def index
    @user = User.all

    respond_to do |format|
      format.html
      format.js { render 'main.js.erb' }
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(
      username: params[:user][:username],
      password: params[:user][:password]
    )
    session[:user_id] = user.id
    redirect_to admin_users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = current_user
    user.update(
    first_name: params[:user][:first_name],
    last_name: params[:user][:last_name],
    age: params[:user][:age],
    education: params[:user][:education]
    )
    redirect_to user_path(user)
  end

  def destroy
    user = current_user
    user.destroy
    redirect_to '/users/sign_in'
  end

  def delete_user
    @user = User.find(params[:id])
    @user.destroy
   
  end

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_types
    ["AdminUser"]
  end

  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/cohort_users_helper.rb
module CohortUsersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Averia+Serif+Libre|Oleo+Script" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">

          <%= render 'shared/nav' %>

          <%= yield %>
        </div>
      </div>
    </div>


    <%= render 'shared/alerts' %>

  </body>
</html>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "School App Alert", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "School App Error", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "School App Notification", sticky: false) %>
<% end %>

app/views/shared/_nav.html.erb
 <nav class="navbar navbar-expand-lg navbar-light  custom-nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active m-2">
       <a class="<%= active?(root_path) %> nav-li">
      <%= link_to "Home", root_path, :class => 'text-white' %>
    </a>
      </li>
      <li class="nav-item m-2">
       <a class="<%= active?(courses_path)%> nav-li">
        <%= link_to "Courses", courses_path, :class => 'text-white' %>
        </a>
      </li>
      <li class="nav-item m-2">
        <a class="<%= active?(cohorts_path)%> nav-li">
          <%= link_to "Cohorts", cohorts_path, :class => 'text-white' %>
        </a>
      </li>
      <li class="nav-item dropdown ml-2">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Options
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          <div class="dropdown-divider"></div>
          <%= link_to "Admin Dashboard", admin_root_path %> 
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/nav.html.erb
<div class="logo">

</div>
<ul class="custom-nav nav nav-pills">
  <li class="nav-item">
    <%= link_to "Home", root_path %>
  </li>
  <li class="nav-item">
     <%= link_to "Courses", courses_path %>
  </li>
  <li class="nav-item">
     <%= link_to "Cohorts", cohorts_path %>
  </li>
  <li class="nav-item dropdown ml-md-auto">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" href="#">Edit User</a> 
        <%= link_to "Edit User", edit_user_registration_path %>
        <a class="dropdown-item" href="#">Another action</a> 
        <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider">
      </div> 
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </div>
  </li>
</ul>